matrix:
  include:
  - language: python
    python:
      - "3.7-dev"
    branches:
      only:
        - master
    install:
      - pip install -r requirements.txt
      - pip install codecov pytest-cov
    script:
      - pytest --cov=./
    after_success:
      - codecov